ecommercemodel/accounts/urls.py
# coding=utf-8

from django.urls import path

from accounts.views import *
from checkout.views import order_list, order_detail


app_name = 'accounts'

urlpatterns = [
    path('', account, name="account"),
    path('registro/', register, name="register"),
    path('alterar-dados/', update_user, name="update_user"),
    path('alterar-senha/', update_password, name="update_password"),
    path('meus-pedidos/', order_list, name="order_list"),
    path('meus-pedidos/<slug:pk>', order_detail, name="order_detail"),


]

ecommercemodel/catalog/urls.py
# coding=utf-8

from django.urls import path

from catalog.views import *

app_name = 'catalog'

urlpatterns = [
    path('', product_list, name="product_list"),
    path('<str:slug>', category, name="category"),
    path('<str:category_father>/<str:slug>', subcategory, name="subcategory"),
    path('produto/<str:slug>', product, name="product"),
]

ecommercemodel/checkout/urls.py
# coding=utf-8

from django.urls import path

from checkout.views import *

app_name = 'checkout'

urlpatterns = [
    path('carrinho/adicionar/<str:slug>', create_cart_item, name="create_cart_item"),
    path('carrinho/', cart_item, name="cart_item"),
    path('limpar-carrinho/', clear_cart_items, name="clear_cart_items"),
    path('finalizando/', checkout_order, name="checkout_order"),
    path('finalizando/pagseguro/<slug:pk>', pagseguro_view, name="pagseguro_view"),
    path('finalizando/paypal/<slug:pk>', paypal_view, name="paypal_view"),
    path('retorno/pagseguro/', pagseguro_notification_view, name="pagseguro_notification_view"),
]

ecommercemodel/ecommercemodel/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf.urls.static import static

from core.views import *
from catalog.views import *
from accounts.views import *
from checkout.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name="index"),
    # path('entrar/', LoginView.as_view(template_name='core/login.html'), name="login"),
    path('sair/', LogoutView.as_view(next_page='index'), name="logout"),
    path('contato/', contact, name="contact"),
    path('produtos/', include('catalog.urls', namespace="catalog")),
    path('conta/', include('accounts.urls', namespace="accounts")),
    path('compras/', include('checkout.urls', namespace="checkout")),
    path('paypal/', include('paypal.standard.ipn.urls')),
]
 
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommercemodel/core/forms.py
# coding=utf-8

from django import forms 
from django.core.mail import send_mail
from django.conf import settings

class ContactForm(forms.Form):

    name = forms.CharField(label="Nome")
    email = forms.EmailField(label="E-mail")
    message = forms.CharField(label="Mensagem", widget=forms.Textarea())

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = f'Nome: {name}\n E-mail: {email}\n{message}'
        send_mail('Teste Django E-Commerce', message, settings.DEFAULT_FROM_EMAIL, [settings.DEFAULT_FROM_EMAIL])

ecommercemodel/core/views.py
# coding=utf-8

import datetime

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, TemplateView, CreateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils.translation import gettext_lazy 

from .forms import ContactForm
from catalog.models import Product, Category

User = get_user_model()

class MyAuthForm(AuthenticationForm):
    error_messages = {
        'invalid_login': gettext_lazy(
            "Por favor, entre com um E-mail e Senha corretos. Note que ambos "
            "os campos diferenciam maiúsculas e minúsculas."
        ),
        'inactive': gettext_lazy("Essa conta está inativa."),
    }

class IndexView(TemplateView, LoginView):  

    template_name = "core/index.html"
    model = Product
    authentication_form = MyAuthForm

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        home_spotlights = Category.objects.filter(home_spotlight=True)
        context['home_spotlight'] = home_spotlights
        return context

index = IndexView.as_view()

def contact(request, template_name = "core/contact.html"):
    success = False
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success = True
        form = ContactForm()
    elif request.method == 'POST':
        messages.error(request, 'Formulário inválido!')
    context = {
        'form': form,
        'sucesso' : success,
    }
    return render(request, template_name, context)

ecommercemodel/design/old/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-BR">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Django E-Commerce{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index' %}" class="navbar-brand">Django E-Commerce</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href='{% url "catalog:product_list" %}'>Produtos</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                {% for category in categories %}
                    <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
                {% endfor %}
              </ul>
            </li>
			<li> 
				<a href="{% url 'contact' %}">Contato</a>
			</li>
          </ul>
          <form class='navbar-form navbar-left' role='search' action='{% url "catalog:product_list" %}'>
            <div class='form-group'>
              <input name='q' type='text' class='form-control' placeholder='Pesquisar Produto...' />
            </div>
          </form>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'checkout:cart_item' %}">Carrinho</a></li>
            <li><a href="{% url 'accounts:account' %}">Minha Conta</a></li>
            <li><a href="{% url 'logout' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'checkout:cart_item' %}">Carrinho</a></li>
            <li><a href="{% url 'accounts:register' %}">Regitrar</a></li>
            <li><a href="{% url 'login' %}">Entrar</a></li>
            {% endif %}
            </ul>
        </div>
      </div>
    </div>
    <div class="container">
    {% block messages %}
      {% for message in messages %}
        <div class='alert alert-{{ message.tags }}'>
          {{ message }}
        </div>
      {% endfor %}
    {% endblock %}
		{% block container %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="">Início</a></li>
			      <li><a href="">Produtos</a></li>
			      <li><a href="">Contato</a></li>
			      <li><a href="">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/pagseguro-popup.js' %}"></script>
    {% block scripts %} {% endblock %}
</body>
</html>

ecommercemodel/design/old/templates/core/contact.html
{% extends "core/base.html" %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Fale conosco</h1>
    {% if success %}
    <div class="alert alert-success">
       Mensagem enviada com sucesso!
    </div>
    {% endif %}
    <form class="form-horizontal" action="" method="POST">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
                <div class="form-group" {% if field.errors %} has-error {% endif %} >
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label_tag }}</label>
                  <div class="col-md-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                      <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

ecommercemodel/design/old/templates/core/index.html
{% extends "core/base.html" %}

{% block container %}
<div class="jumbotron page-header">
  <h1>Django E-Commerce</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  <p><a class="btn btn-primary">Saiba mais</a></p>
</div>
{% endblock %}

ecommercemodel/design/old/templates/core/login.html
{% extends "core/base.html" %}

{% load widget_tweaks %}

{% block title %}Entrar | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.password class="form-control" %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

ecommercemodel/design/old/templates/core/pagination.html
{% if page_obj.has_other_pages %}
<div class="row">
    <div class="col-md-12">
        <nav>
          <ul class="pagination">
              {% for page in paginator.page_range %}
              <li{% if page_obj.number == page %} class="active"{% endif %}><a href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
              {% endfor %}
          </ul>
        </nav>
    </div>
</div>
{% endif %}

ecommercemodel/design/old/templates/core/pagination2.old.html
{% if page_obj.has_other_pages %}
    <div class="row">
        <div class="col-md-12">
            <nav>
                <ul class="pagination">
                    {% for page in paginator.page_range %}
                        <li{% if page_obj.number == page %} class="active"{% endif %}>
                            <a href="?page={‌{ page }}{‌{ getvars }}">{‌{ page }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
{% endif %}