ecommercemodel/accounts/urls.py
# coding=utf-8

from django.urls import path

from accounts.views import *
from checkout.views import order_list, order_detail


app_name = 'accounts'

urlpatterns = [
    path('', account, name="account"),
    path('registro/', register, name="register"),
    path('alterar-dados/', update_user, name="update_user"),
    path('alterar-senha/', update_password, name="update_password"),
    path('meus-pedidos/', order_list, name="order_list"),
    path('meus-pedidos/<slug:pk>', order_detail, name="order_detail"),


]

ecommercemodel/catalog/urls.py
# coding=utf-8

from django.urls import path

from catalog.views import *

app_name = 'catalog'

urlpatterns = [
    path('', product_list, name="product_list"),
    path('<str:slug>', category, name="category"),
    path('<str:category_father>/<str:slug>', subcategory, name="subcategory"),
    path('produto/<str:slug>', product, name="product"),
]

ecommercemodel/ecommercemodel/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf.urls.static import static

from core.views import *
from catalog.views import *
from accounts.views import *
from checkout.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name="index"),
    # path('entrar/', LoginView.as_view(template_name='core/login.html'), name="login"),
    path('sair/', LogoutView.as_view(next_page='index'), name="logout"),
    path('contato/', contact, name="contact"),
    path('produtos/', include('catalog.urls', namespace="catalog")),
    path('conta/', include('accounts.urls', namespace="accounts")),
    path('compras/', include('checkout.urls', namespace="checkout")),
    path('paypal/', include('paypal.standard.ipn.urls')),
]
 
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommercemodel/accounts/models.py
# coding=utf-8

import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin

class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField("Usuário", max_length=30, unique=True, validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'), "Informe um nome de usuário válido. Este valor pode conter apenas letras, números e os seguintes caracteres @/./+/-/_.", 'invalid')], help_text="Obrigatório. Insira aqui um nome de usuário com 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.")
    email = models.EmailField("E-mail", unique=True, help_text="Obrigatório. Insira aqui um e-mail válido.")
    name = models.CharField("Nome completo", blank=False, max_length=100, help_text="Obrigatório. Insira aqui seu nome completo.")
    is_active = models.BooleanField("Ativo", blank=True, default=True, help_text="Indica que este usuário está ativo para logar.")
    is_staff = models.BooleanField("Membro da equipe", blank=True, default=False, help_text="Indica que este usuário é membro da equipe de administradores.")
    date_joined = models.DateTimeField("Data do Registro", auto_now_add=True)
    avatar = models.ImageField("Imagem de Perfil", upload_to="accounts/profile_avatar", null=True, blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(' ')[0]

ecommercemodel/accounts/forms.py
# coding=utf-8

from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'name', 'email']
    

class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'is_active', 'is_staff',]

ecommercemodel/accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView, UpdateView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin # View Baseada em Classe
#from django.contrib.auth.decorators import login_required # View Baseada em Função
from django.contrib.auth.forms import PasswordChangeForm

from .models import User
from .forms import UserAdminCreationForm

class AccountView(LoginRequiredMixin, TemplateView):

    template_name = 'accounts/account.html'

account = AccountView.as_view()

class RegisterView(CreateView):

    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')

register = RegisterView.as_view()

class UpdateUserView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('accounts:account')

    def get_object(self):
        return self.request.user

update_user = UpdateUserView.as_view()

class UpdatePasswordView(LoginRequiredMixin, FormView):

    template_name = 'accounts/update_password.html'
    success_url = reverse_lazy('accounts:account')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

update_password = UpdatePasswordView.as_view()

ecommercemodel/accounts/templates/accounts/account.html
{% extends "base.html" %}

{% block title %}Minha Conta{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'accounts:account' %}">Início</a></li>
  <li class="active">Minha Conta</li>
</ol>
<div class="row">
    <div class="col-md-4">
        <div class="list-group">
          <a href="{% url 'accounts:account' %}" class="list-group-item active">Minha Conta</a>
          <a href="{% url 'accounts:update_user' %}" class="list-group-item">Alterar Dados</a>
          <a href="{% url 'accounts:order_list' %}" class="list-group-item">Meus Pedidos</a>
          <a href="{% url 'accounts:update_password' %}" class="list-group-item">Alterar Senha</a>
        </div>
    </div>
    <div class="col-md-8">
        {% block accounts_container %}
            <h2>Bem vindo {{ user }}</h2>
        {% endblock %}
    </div>
</div>
{% endblock %}

ecommercemodel/accounts/templates/accounts/update_password.html
{% extends "accounts/account.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Senha{% endblock %}

{% block accounts_container %}
    <h2>Alterar Senha</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

ecommercemodel/accounts/templates/accounts/update_user.html
{% extends "accounts/account.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Dados{% endblock %}

{% block accounts_container %}
    <h2>Alterar Dados</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}