ecommercemodel/catalog/urls.py
# coding=utf-8

from django.urls import path

from catalog.views import *

app_name = 'catalog'

urlpatterns = [
    path('', product_list, name="product_list"),
    path('<str:slug>', category, name="category"),
    path('<str:category_father>/<str:slug>', subcategory, name="subcategory"),
    path('produto/<str:slug>', product, name="product"),
]

ecommercemodel/checkout/urls.py
# coding=utf-8

from django.urls import path

from checkout.views import *

app_name = 'checkout'

urlpatterns = [
    path('carrinho/adicionar/<str:slug>', create_cart_item, name="create_cart_item"),
    path('carrinho/', cart_item, name="cart_item"),
    path('limpar-carrinho/', clear_cart_items, name="clear_cart_items"),
    path('finalizando/', checkout_order, name="checkout_order"),
    path('finalizando/pagseguro/<slug:pk>', pagseguro_view, name="pagseguro_view"),
    path('finalizando/paypal/<slug:pk>', paypal_view, name="paypal_view"),
    path('retorno/pagseguro/', pagseguro_notification_view, name="pagseguro_notification_view"),
]

ecommercemodel/ecommercemodel/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf.urls.static import static

from core.views import *
from catalog.views import *
from accounts.views import *
from checkout.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name="index"),
    # path('entrar/', LoginView.as_view(template_name='core/login.html'), name="login"),
    path('sair/', LogoutView.as_view(next_page='index'), name="logout"),
    path('contato/', contact, name="contact"),
    path('produtos/', include('catalog.urls', namespace="catalog")),
    path('conta/', include('accounts.urls', namespace="accounts")),
    path('compras/', include('checkout.urls', namespace="checkout")),
    path('paypal/', include('paypal.standard.ipn.urls')),
]
 
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommercemodel/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.conf import settings
from django.utils.timezone import now
from django.core.signals import request_started

class Category(models.Model):

    name = models.CharField("Nome", max_length=100, unique=True, help_text='Determine uma subcategoria para que possa ser associada ao produtos.')
    slug = models.SlugField('Identificador', max_length=100)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)
    image = models.ImageField('Imagem', upload_to='categories', blank=True, null=True, help_text="Opcional. Envie uma foto para a categoria.")
    home_spotlight = models.BooleanField("Destaque na página inicial", default=False, help_text="Determina se essa Categoria deve ser inclusa nos Destaques da Página Inicial. Geralmente Categoria em destaque possuem promoções.")
    in_navbar = models.BooleanField("Incluir na Barra Superior?", default=False, help_text="Determina se essa Categoria deve ser inclusa na barra superior do site.")


    class Meta: 
        verbose_name = 'Categoria'
        verbose_name_plural = "Categorias"
        ordering = ['name']

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug': self.slug})

class Subcategory(models.Model):

    name = models.CharField("Nome", max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    category_father = models.ForeignKey('catalog.Category', verbose_name="Categoria", on_delete=models.CASCADE,null=False, blank=False, help_text="Determine a categoria o essa subcategoria será associada.")
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta: 
        verbose_name = 'Subcategoria'
        verbose_name_plural = "Subcategorias"
        unique_together = (('name', 'category_father'),)
        ordering = ['name']

    def __str__(self):
        return f'{self.category_father} - {self.name}'
        # return self.name

    def get_absolute_url(self):
        return reverse('catalog:subcategory', kwargs={'category_father': self.category_father.slug, 'slug': self.slug})

class Product(models.Model):
    
    id = models.AutoField('Código', primary_key=True)
    name = models.CharField("Nome", max_length=100, blank=False, null=False, unique=True, help_text="Obrigatório. Nome do Produto, de maior destaque na página.")
    slug = models.SlugField('Identificador', max_length=100, help_text="Não alterar esse campo.")
    category = models.ForeignKey('catalog.Category', related_name='category', verbose_name="Categoria", on_delete=models.CASCADE, null=True, blank=False, help_text="Determine uma categoria para o produto.")
    subcategory = models.ForeignKey('catalog.Subcategory', verbose_name="Subcategoria", on_delete=models.CASCADE, null=True, blank=False, help_text="Determine uma subcategoria para o produto.")
    description = models.TextField('Descrição', blank=False, null=False, max_length=85, help_text="Obrigatório. Uma descrição breve do Produto. Max. 85 caracteres.")
    description_big = models.TextField('Descrição Detalhada', blank=True, null=True, max_length=800, help_text="Opcional. Uma descrição longa do Produto. Max. 800 caracteres.")
    price = models.DecimalField("Preço", decimal_places=2, max_digits=8, help_text="Obrigatório. Determine um preço para o Produto.")
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)
    start_date = models.DateTimeField('Data de Exibição', null=True, blank=True, help_text="Opcional, defina uma data futura, para que o Produto seja exibido somente a partir dela.")
    end_date = models.DateTimeField('Data de Expiração', null=True, blank=True, help_text="Opcional, defina uma data futura, para que o Produto deixe de ser exibido a partir dela.")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Criado por",related_name="criado_por", on_delete=models.CASCADE,)
    is_active = models.BooleanField("Ativo", default=True, help_text="Determina se esse Produto deve ser tratado como ativo. Desmarque isso em vez de excluir produtos.")
    spotlight = models.BooleanField("Destaque", default=False, help_text="Determina se esse Produto deve ser tratado como Destaque. Geralmente produtos em destaque possuem promoções.")

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = "Produtos"
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'slug': self.slug})

class ProductImages(models.Model):

    product = models.ForeignKey(Product, verbose_name="Produto", related_name="images", on_delete=models.CASCADE)
    image = models.ImageField('Imagem', upload_to='products', blank=False, null=False, help_text="Obrigatório. Envie uma foto para o produto.")
    thumbnail = models.BooleanField("Thumbnail", default=False, help_text="Determina se essa imagem deve ser tratada como thumbnail do produto. Thumbnail aparecem primeiro.")
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Imagem'
        verbose_name_plural = 'Imagens'
        # unique_together = (('product', 'thumbnail'),)


    def __str__(self):
        return f'Imagem de "{self.product}"'

ecommercemodel/catalog/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.views import generic 
from django.db import models
from watson import search as watson
from django.db.models import signals
# from django.views.decorators.cache import cache_page


from .models import Product, Category, Subcategory

class ProductListView(generic.ListView):

    template_name = "catalog/product_list.html"
    context_object_name = 'product_list'
    paginate_by = 3

    def get_queryset(self):
        queryset = Product.objects.filter(is_active=True)
        q = self.request.GET.get('q', '')
        if q:
            if queryset.filter(models.Q(pk__iexact=q)):
                return queryset.filter(models.Q(pk__iexact=q))
            else:
                return watson.filter(queryset, q)
        return queryset


class CategoryListView(generic.ListView):
    
    context_object_name = 'product_list'
    template_name = "catalog/category.html"
    paginate_by = 3

    def get_queryset(self):
        return Product.objects.filter(is_active=True, category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context

class SubcategoryListView(generic.ListView):
    
    context_object_name = 'product_list'
    template_name = "catalog/category.html"
    paginate_by = 3

    def get_queryset(self):
        return Product.objects.filter(is_active=True, category__slug=self.kwargs['category_father'], subcategory__slug=self.kwargs['slug'],)

    def get_context_data(self, **kwargs):
        context = super(SubcategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Subcategory, slug=self.kwargs['slug'], category_father__slug=self.kwargs['category_father'])
        return context

# @cache_page(60 * 1)
def product(request, slug, template_name = "catalog/product.html"):
    product = Product.objects.filter(is_active=True).get(slug=slug)
    context = {
        "product" : product,
    }
    return render(request, template_name, context)

product_list = ProductListView.as_view()
category = CategoryListView.as_view()
subcategory = SubcategoryListView.as_view()

ecommercemodel/catalog/templates/catalog/_product.html
{% load thumbnail %}
{% load static %}

<div class="col-sm-6 col-md-4">
    <div class="card mb-5 border-0 bg-light">
        <a href="{{ product.get_absolute_url }}">
            {% for image in product.images.all %}
            {% if image.thumbnail %}
            <img class="card-img-top" src="{{ image.image|thumbnail_url:'product_image' }}" alt="" />
            {% endif %}
            {% empty %}
            <img src="http://placehold.it/350x250" alt="" />
            {% endfor %}
        </a>
        <div class="card-body">
            <a href="{{ product.get_absolute_url }}">
              <p class="card-title h6 mb-2"> {{ product.name }} </p>
            </a>
            <a href="{{ category.get_absolute_url }}">
              <p class="card-subtitle mb-0 text-muted"> {{ category.name }} </p>
            </a>
        <!-- <a class="shadow-none btn btn-transparent card-link ml-0 float-right btn-gif p-1"> <img class="bg-gif" data-in='{% static "new/img/heart-in.gif" %}' data-out='{% static "new/img/heart-out.gif" %}' src='{% static "new/img/heart.svg" %}'> </a> -->
            <a class="text-dark" href="{{ product.get_absolute_url }}">
                <p class='card-text pt-1'><s class="text-muted"> R$180,00 </s><span class="font-weight-bold ml-1"> R$ {{ product.price }} </span></p>
            </a>
        </div>
        <div class="card-footer py-0 text-muted bottom d-flex">
            <a href="#"><i class="text-warning fa fa-star"></i></a>
            <a href="#"><i class="text-warning fa fa-star"></i></a>
            <a href="#"><i class="text-warning fa fa-star"></i></a>
            <a href="#"><i class="text-warning fa fa-star"></i></a>
            <a href="#"><i class="text-warning fa fa-star-half-o" aria-hidden="true"></i></a>
            {% comment %} <a href="#"><i class="text-warning fa fa-star-half" aria-hidden="true"></i></a> {% endcomment %}
            <p class="ml-20 mb-0">25 Reviews</p>
        </div>
    </div>
</div>

ecommercemodel/catalog/templates/catalog/category.html
{% extends "core/base.html" %}

{% load pagination %}

{% block title %}
    {{ current_category }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>{{ current_category }}</h1>
</div>
<div class="row">
    {% for product in product_list %}
    {% include 'catalog/_product.html' %}
    {% endfor %}
</div>
{% pagination request paginator page_obj %}
{% endblock %}

ecommercemodel/catalog/templates/catalog/product.html
{% extends "core/base.html" %}

{% block title %}
    {{ product }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>{{ product }}</h1>
</div>
<div class="row">
  <div class="col-sm-4">
      <a href="#" class="thumbnail">
            {% if product.images %}
            {% for image in product.images.all %}
            {% if image.thumbnail %}
            <img src="{{ image.image.url }}" alt="" />
            {% endif %}
            {% endfor %}
            {% else %}
            <img src="http://placehold.it/350x250" alt="" />
            {% endif %}
      </a>
  </div>
  <div class="col-sm-8">
      <p class="text-right">
          <a href="{% url 'checkout:create_cart_item' product.slug %}" class="btn btn-success">Adicionar ao Carrinho</a>
      </p>
      {{ product.description|linebreaks }}
  </div>
</div>
{% endblock %} 
  

ecommercemodel/catalog/templates/catalog/product_list.html
{% extends "core/base.html" %}
{% load static %}

{% load pagination %}

{% block title %}
    Listagem de Produtos | {{ block.super }}
{% endblock %}

{% block header_area  %}
 {{ block.super }}
{% endblock %}

{% block banner_area %}
 {{ block.super }}
{% endblock %}

{% block index_carousel %}

    <div class="container"> 
        <div class="row justify-content-sm-center">
                {% for product in product_list %}
                    {% include 'catalog/_product.html' %}
                {% endfor %}
            </div>
        </div>
    </div>

{% pagination request paginator page_obj %}

{% endblock %}

{% block scripts %}

<script type='text/javascript'>
$(function(){
    $('.cart-item-add').on('click', function(e){
        e.preventDefault();
        $.ajax({
            url: $(this).attr('href'),
            dataType: 'json',
            success: function(data, textStatus, jqXHR){
                //pass
            }
        });
    });
});

</script>

{% endblock %}