ecommercemodel/accounts/urls.py
# coding=utf-8

from django.urls import path

from accounts.views import *
from checkout.views import order_list, order_detail


app_name = 'accounts'

urlpatterns = [
    path('', account, name="account"),
    path('registro/', register, name="register"),
    path('alterar-dados/', update_user, name="update_user"),
    path('alterar-senha/', update_password, name="update_password"),
    path('meus-pedidos/', order_list, name="order_list"),
    path('meus-pedidos/<slug:pk>', order_detail, name="order_detail"),


]

ecommercemodel/catalog/urls.py
# coding=utf-8

from django.urls import path

from catalog.views import *

app_name = 'catalog'

urlpatterns = [
    path('', product_list, name="product_list"),
    path('<str:slug>', category, name="category"),
    path('<str:category_father>/<str:slug>', subcategory, name="subcategory"),
    path('produto/<str:slug>', product, name="product"),
]

ecommercemodel/checkout/urls.py
# coding=utf-8

from django.urls import path

from checkout.views import *

app_name = 'checkout'

urlpatterns = [
    path('carrinho/adicionar/<str:slug>', create_cart_item, name="create_cart_item"),
    path('carrinho/', cart_item, name="cart_item"),
    path('limpar-carrinho/', clear_cart_items, name="clear_cart_items"),
    path('finalizando/', checkout_order, name="checkout_order"),
    path('finalizando/pagseguro/<slug:pk>', pagseguro_view, name="pagseguro_view"),
    path('finalizando/paypal/<slug:pk>', paypal_view, name="paypal_view"),
    path('retorno/pagseguro/', pagseguro_notification_view, name="pagseguro_notification_view"),
]

ecommercemodel/ecommercemodel/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf.urls.static import static

from core.views import *
from catalog.views import *
from accounts.views import *
from checkout.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name="index"),
    # path('entrar/', LoginView.as_view(template_name='core/login.html'), name="login"),
    path('sair/', LogoutView.as_view(next_page='index'), name="logout"),
    path('contato/', contact, name="contact"),
    path('produtos/', include('catalog.urls', namespace="catalog")),
    path('conta/', include('accounts.urls', namespace="accounts")),
    path('compras/', include('checkout.urls', namespace="checkout")),
    path('paypal/', include('paypal.standard.ipn.urls')),
]
 
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommercemodel/checkout/models.py
# coding=utf-8

from django.db import models
from django.conf import settings

# from pagseguro.api import PagSeguroItem, PagSeguroApi
from pagseguro.signals import  notificacao_recebida
import pagseguro 

from catalog.models import Product

class CartItemManager(models.Manager):

    def add_item(self, cart_key, product):

        if self.filter(cart_key=cart_key, product=product).exists():
            created = False
            cart_item = self.get(cart_key=cart_key, product=product)
            cart_item.quantity = cart_item.quantity + 1
            cart_item.save()
        else:
            created = True
            cart_item = CartItem.objects.create(
                cart_key=cart_key, product=product, price=product.price)
        return cart_item, created


class CartItem(models.Model):

    cart_key = models.CharField('Chave do Carrinho', max_length=40, db_index=True)
    product = models.ForeignKey('catalog.Product', verbose_name='Produto', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', on_delete=models.CASCADE, null=True)

    objects = CartItemManager()

    class Meta:
        verbose_name = 'Item do Carrinho'
        verbose_name_plural = 'Itens dos Carrinhos'
        unique_together = (('cart_key', 'product'),)

    def __str__(self):
        return f'{self.product}'

class OrderManager(models.Manager):

    def create_order(self, user, cart_items):
        order = self.create(user=user)
        for cart_item in cart_items:
            order_item = OrderItem.objects.create(order=order, quantity=cart_item.quantity, 
            product=cart_item.product, price=cart_item.price)
        
        return order

class Order(models.Model):
    
    STATUS_CHOICES = (
        ('1', 'Aguardando Pagamento'),
        ('2', 'Pagamento em Análise'),
        ('3', 'Pagamento Autorizado'),
        ('7', 'Cancelado'),
    )

    PAYMENT_OPTION_CHOICES = (
        ("boletobancario", 'Boleto Bancário'),
        ("pagseguro", 'PagSeguro'),
        ("paypal", 'PayPal'),
    )

    id = models.AutoField('ID do Pedido', primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', on_delete=models.CASCADE,)
    status = models.CharField('Situação', choices=STATUS_CHOICES, max_length=30, default=None, blank=True, null=True)
    payment_option = models.CharField('Modo de Pagamento', choices=PAYMENT_OPTION_CHOICES, max_length=30, default=None, blank=True, null=True)
    created = models.DateTimeField('Data de Criação', auto_now_add=True)
    modified = models.DateTimeField('Data de Modificação', auto_now=True)
    
    objects = OrderManager()

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def products(self):
        products_ids = self.items.values_list('product')
        return Product.objects.filter(pk__in=products_ids)
    
    def total_price(self):
        aggregate_queryset = self.items.aggregate(total=models.Sum(models.F('price')
         * models.F('quantity'), output_field=models.DecimalField()))
        return aggregate_queryset['total']


#### pagseguro.api Django

    # def pagseguro(self): 
    #     self.payment_option = 'pagseguro'
    #     self.save()
    #     pg = PagSeguroApi(reference=self.id, 
    #                       token=settings.PAGSEGURO_TOKEN, 
    #                       email=settings.PAGSEGURO_EMAIL,
    #                       senderEmail=self.user.email, 
    #                       senderName=self.user.name)
    #     for item in self.items.all():
    #         pagseg_item = PagSeguroItem(id=item.product.pk, 
    #                                     description=item.product.name,
    #                                     amount=f'{item.price:.2f}',
    #                                     quantity=item.quantity,
    #                                     shipping_cost=None, 
    #                                     weight=None)
    #         pg.add_item(pagseg_item)
    #     return pg

#### Módulo Python pagseguro

    def pagseguro(self):
        self.payment_option = 'pagseguro'
        self.save()
        pg = pagseguro.PagSeguro(token=settings.PAGSEGURO_TOKEN, 
                       email=settings.PAGSEGURO_EMAIL,
                       config={'sandbox': settings.PAGSEGURO_SANDBOX})
        pg.sender = {"name": self.user.name,
                     "area_code": None,
                     "phone": None,
                     "email": self.user.email,}
        pg.reference_prefix = ''
        pg.shipping = None
        pg.reference = self.id

        for item in self.items.all():
            pg.items.append({'id': item.product.pk, 
                             'description': item.product.name,
                             'amount': f'{item.price:.2f}',
                             'quantity': item.quantity,
                             'shipping_cost': None, 
                             'weight': None
                            })
        return pg

    def update_pagseguro_status(self, status):

        STATUS_MAP = {
        '1': 'Aguardando Pagamento',
        '2': 'Pagamento em Análise',
        '3': 'Pagamento Autorizado',
        '7': 'Cancelado',
        }

        if status in STATUS_MAP:
            self.status = status
        else:
            self.status = '2'
        self.save()

    def __str__(self):
        return f'#{self.id:0>6}'

#### Módulo Python/Django PayPal

    def paypal(self):
        self.payment_option = 'paypal'
        self.status = '1'
        self.save()
        paypal_dict = {'upload': '1',
                       'business': settings.PAYPAL_EMAIL,
                       'invoice': self.pk,
                       'cmd': '_cart',
                       'currency_code': 'BRL',
                       'charset': 'utf-8',}
        index = 1
        for item in self.items.all():
            paypal_dict[f'amount_{index}'] = f'{item.price:.2f}'
            paypal_dict[f'item_name_{index}'] = item.product.name
            paypal_dict[f'quantity_{index}'] = item.quantity
            index += 1
        return paypal_dict

class OrderItem(models.Model):

    order = models.ForeignKey(Order, verbose_name="Pedido", related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey('catalog.Product', verbose_name='Produto', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    class Meta:
        verbose_name = 'Item do Pedido'
        verbose_name_plural = 'Itens dos Pedidos'

    def __str__(self):
        return f'Pedido #{self.pk:0>6} - Produto {self.product}'

#### Signals

## Excluir item ao zerar
def post_save_cart_item(instance, **kwargs):
    if instance.quantity < 1:
        instance.delete()

models.signals.post_save.connect(post_save_cart_item, sender=CartItem, dispatch_uid='post_save_cart_item')

ecommercemodel/design/old/templates/checkout/cart.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Carrinho de compras{% endblock %}

{% block container %} 

<div class="container margin-top">
  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">Início</a></li>
    <li class="active">Carrinho de Compras</li>
  </ol>
<div class="page-header">
<h1>Carrinho de Compras</h1>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form class="" action="" method=post>
          {% csrf_token %}
          {{ formset.management_form }}
            <table class="table table-bordered">
                <thead>
                    <th>
                        ID
                    </th>
                    <th>
                        Nome
                    </th>
                    <th>
                        Preço
                    </th>
                    <th style="width: 10%;">
                        Quantidade
                    </th>
                    <th>
                    
                    </th>
                </thead>
                <tbody>
                  {% for form in formset %}

                    <tr>
                      <td>
                          {{ form.instance.product.pk }}
                      </td>
                      <td>
                          {{ form.instance.product }}
                      </td>
                      <td>
                          R$ {{ form.instance.product.price | floatformat:'2' }}
                      </td>
                      <td>
                        {% render_field form.quantity class='form-control' %}
                      </td>
                      <td class="text-center">
                        <button value='on' class='btn btn-danger btn-sm' type="submit" name='{{ form.DELETE.html_name }}'>Remover</button>
                        {{ form.id }}
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
            </table>
            <p class="text-right">
                {% if formset|length == 0 %}
                <a class="pull-left btn btn-danger" disabled>Limpar Carrinho</a>
                {% else %}
                <a href="{% url 'checkout:clear_cart_items' %}" class="pull-left btn btn-danger">Limpar Carrinho</a>
                {% endif %}
                <button type="submit" class="btn btn-primary" name="button">Atualizar Carrinho</button></li>
                <a href="{% url 'checkout:checkout_order' %}" class="btn btn-success">Finalizar Compra</a>
            </p>
        </form>
    </div>
</div>

{% endblock %}

ecommercemodel/design/old/templates/checkout/checkout.html
{% extends "base.html" %}

{% block title %}
Finalização da Compra
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li><a href="{% url 'checkout:cart_item' %}">Carrinho de Compras</a></li>
  <li class="active">Finalização da Compra</li>
</ol>
<div class="page-header">
    <h1>Forma de pagamento</h1>
</div>
<div class="row">
    <div class="col-md-12">
        <p>
            Pedido {{ order }}
        </p>
    </div>
    <div class="col-md-2 col-md-offset-2">
        <a href='' class='btn btn-success'>Boleto Bancário</a>
    </div>
    <div class="col-md-2">
        <button onclick=pagseguro_popup("{% url 'checkout:pagseguro_view' order.id %}") class='btn btn-success'>PagSeguro</button>
        <!-- <a href='{% url "checkout:pagseguro_view" order.id %}' class='btn btn-success'>PagSeguro</a> -->
    </div>
    <div class="col-md-2">
        <button onclick=pagseguro_popup("{% url 'checkout:paypal_view' order.id %}") class='btn btn-success'>PayPal</button>
    </div>

</div>
{% endblock %}

ecommercemodel/design/old/templates/checkout/order_detail.html
{% extends "accounts/account.html" %}

{% load pagination %}

{% load widget_tweaks %}

{% block title %}Pedido {{ order }}{% endblock %}

{% block accounts_container %}
<h2>Pedido {{ order }}</h2>
<dl class='dl-horizontal'>
  <dt>Data:</dt>
  <dd>{{ object.created|date:'d/m/Y \à\s H:i' }}</dd>
  <dt>Forma de Pagamento:</dt>
  <dd>{{ object.get_payment_option_display }}</dd>
  <dt>Situação:</dt>
  {% if object.status == '1' %} 
    <dd style="font-weight: bold; color:#e7c501">{{ object.get_status_display }}</dd> 
  {% elif object.status == '2' %}
    <dd style="font-weight: bold; color:#1E90FF">{{ object.get_status_display }}</dd> 
  {% elif object.status == '3' %}
    <dd style="font-weight: bold; color:#32CD32">{{ object.get_status_display }}</dd> 
  {% elif object.status == '7' %}
    <dd style="font-weight: bold; color:#EE0000">{{ object.get_status_display }}</dd> 
  {% endif %}
  <dt>Total do Pedido:</dt>
  <dd style="font-weight: bold">R$ {{ object.total_price | floatformat:'2' }}</dd>
</dl>
<h3>Itens do Pedido</h3>
{% for item in object.items.all %}
<dl class='dl-horizontal'>
    <dt>Produto:</dt>
    <dd>{{ item.product }}</dd>
    <dt>Quantidade:</dt>
    <dd>{{ item.quantity }}</dd>
    <dt>Preço:</dt>
    <dd>R$ {{ item.price | floatformat:'2' }}</dd>
</dl>
{% endfor %}
{% pagination request paginator page_obj %}
{% endblock %}

ecommercemodel/design/old/templates/checkout/order_list.html
{% extends "accounts/account.html" %}

{% load pagination %}

{% load widget_tweaks %}

{% block title %}Meus Pedidos{% endblock %}

{% block accounts_container %}
    <h2>Meus Pedidos</h2>
    <table class="table table-bordered">
            <thead>
                <th class="text-center">
                    Número do Pedido
                </th>
                <th class="text-center">
                    Data
                </th>
                <th class="text-center">
                    Pagamento
                </th>
                <th class="text-center">
                    Situação
                </th>
                <th class="text-center">
                    Produtos
                </th>
                <th class="text-center">
                    Valor Total
                </th>
            </thead>
            <tbody>
              {% for order in object_list %}
                <tr>
                  <td class="text-center">
                    <a href="{% url 'accounts:order_detail' order.id %}">{{ order }}</a> 
                  </td>
                  <td class="text-center">
                    {{ order.created|date:'d/m/Y' }}
                  </td>
                  <td class="text-center">
                    {{ order.get_payment_option_display }}
                  </td>
                  <td class="text-center">
                    {{ order.get_status_display }}
                  </td>
                  <td >
                    {% for product in order.products %}
                    {{ product.name }}{% if not forloop.last %};<br/>{% else %}.{% endif %}
                    {% endfor %}
                  </td>
                  <td class="text-center">
                     R$ {{ order.total_price | floatformat:'2' }}
                    </td>
                </tr>
              {% endfor %}
            </tbody>
        </table>
{% pagination request paginator page_obj %}
{% endblock %}

ecommercemodel/design/old/templates/checkout/paypal.html
{% extends "base.html" %}

{% block title %}
Pagamento via Paypal
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li><a href="{% url 'checkout:cart_item' %}">Carrinho de Compras</a></li>
  <li class="active">Pagamento via Paypal</li>
</ol>
<div class="page-header">
    <h1>Você está sendo redirecionado para o paypal</h1>
</div>
<div id="paypal" class="row">
    {{ form.render }}
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(function(){
        $("#paypal form").submit();
    });
</script>
{% endblock %}